apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: localhost:32000/conference-webapp:1.0
          imagePullPolicy: Always
          ports:
          - name: webapp
            containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready.json
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
      imagePullSecrets:
        - name: payara-conference

---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - name: web
    port: 8080
